### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by arjun-crri** [jnunemaker/twitter-app#1]
Hey Dude,

Can you help. I cloned you app and tried to run it, but i am getting the 401 error.
I did a check found a weird issue.

When I check using logger in code, I see that line #6 in session controller at "oauth.set_callback_url(finalize_session_url)" is not working properly. Its failing here.

Further checking I found that oauth object is getting created using oauth.inspect but oauth.request_token.token is not returning anything.

Now the very weird part is that, when I run a series of commands in console, I able to get to the URL for Accept/Deny twitter page for the app, meaning the methods seems to be running at console fine.

Can you please kindly help. Or is it that OAuth is not working now?

Regards,
Arjun Ghosh

**Comment by jnylund** [comment]
Same issue for me.

**Comment by jnylund** [comment]
ok, I figured out, you have to register an app here: http://twitter.com/apps/new, then take the token and the secret and set them in environment variables see twitter.rb in initializers: ConsumerToken, ConsumerSecret = ENV['TWITTER_TOKEN'], ENV['TWITTER_SECRET'] 

after that it seems to work for me!

**Comment by cmaxw** [comment]
New trick! Make sure that your application is set as a Browser app, not a Client app. It'll blow up assigning the callback url if you don't.
